# Generated by Django 5.2.15 on 2026-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="会社名")),
                ("ticker", models.CharField(max_length=20, verbose_name="ティッカー")),
                (
                    "market",
                    models.CharField(
                        choices=[("jp", "日本株"), ("us", "米国株")],
                        max_length=2,
                        verbose_name="市場区分",
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, verbose_name="保有株数"
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="投資元本（円）"
                    ),
                ),
                (
                    "buy_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="買付額"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
