# Generated by Django 5.2.15 on 2026-06-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_stock_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="buy_price",
        ),
    ]
